export const GET_ALL_PURCHASE_ADMIN = 'GET_ALL_PURCHASE_ADMIN';
export const SET_ALL_PURCHASE_ADMIN = 'SET_ALL_PURCHASE_ADMIN';
export const SET_ORDER_DELIVERY = 'SET_ORDER_DELIVERY';
export const GET_DRIVER_LIST = 'GET_DRIVER_LIST';
export const SET_DRIVER_LIST = 'SET_DRIVER_LIST';
export const SET_CHANNEL = 'SET_CHANNEL';

