export const GET_ACTIVE_PURCHASE = 'GET_ACTIVE_PURCHASE';
export const SET_ACTIVE_PURCHASE = 'SET_ACTIVE_PURCHASE';
export const SET_FINISH_ORDER = 'SET_FINISH_ORDER';
export const GET_TOKEN_CHAT = 'GET_TOKEN_CHAT';
export const SET_TOKEN_CHAT = 'SET_TOKEN_CHAT';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
