export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SELECTED_PRODUCTS = 'GET_SELECTED_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_SELECTED_PRODUCTS = 'FETCH_SELECTED_PRODUCTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_BASKET = 'SET_BASKET';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const SET_PRODUCT_DISABLE = 'SET_PRODUCT_DISABLE';
export const SET_PRODUCT_ENABLE = 'SET_PRODUCT_ENABLE';

export const GET_SOFT_DELETED_MENU = 'GET_SOFT_DELETED_MENU';
export const GET_SOFT_DELETED_MENU_SUCCESS = 'GET_SOFT_DELETED_MENU_SUCCESS';

export const DELETE_SOFT_MENU = 'DELETE_SOFT_MENU';
export const RESTORE_DELETE_MENU = 'RESTORE_DELETE_MENU';
