export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SELECTED_PRODUCTS = 'GET_SELECTED_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_SELECTED_PRODUCTS = 'FETCH_SELECTED_PRODUCTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_BASKET = 'SET_BASKET';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
